force-app/main/default/objects/NEOS_Matter__c/NEOS_Matter__c.object-meta.xml
<CustomObject>
    <label>Matter</label>
    <nameField>
        <label>Matter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NEOS_Matter__c/fields/Case_Title__c.field-meta.xml
<CustomField>
    <fullName>Case_Title__c</fullName>
    <label>Case Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NEOS_Matter__c/fields/Senior_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Senior_Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Senior Attorney</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Senior Counsel</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Managing Attorney</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>NEOS_Matters1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subtask_Template__c/Subtask_Template__c.object-meta.xml
<CustomObject>
    <label>Subtask Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subtask Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subtask_Template_Item__c/Subtask_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Subtask Template Item</label>
    <nameField>
        <displayFormat>STI-{0000}</displayFormat>
        <label>Subtask Template Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subtask Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subtask_Template_Item__c/fields/Assignee_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Type__c</fullName>
    <label>Assignee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Static User</fullName>
                <default>true</default>
                <label>Static User</label>
            </value>
            <value>
                <fullName>Dynamic Matter Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subtask_Template_Item__c/fields/Dynamic_Assignee_Field__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_Assignee_Field__c</fullName>
    <description>API name of the User lookup field on NEOS_Matter__c to read the assignee from (e.g. Senior_Attorney__c), used when Assignee_Type__c is &quot;Dynamic Matter Field&quot;.</description>
    <label>Dynamic Assignee Field</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subtask_Template_Item__c/fields/Sequence_Order__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Order__c</fullName>
    <label>Sequence Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subtask_Template_Item__c/fields/Static_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Static_Assignee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Static Assignee</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Subtask Template Items (Static Assignee)</relationshipLabel>
    <relationshipName>Subtask_Template_Items_Static</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subtask_Template_Item__c/fields/Subtask_Template__c.field-meta.xml
<CustomField>
    <fullName>Subtask_Template__c</fullName>
    <label>Subtask Template</label>
    <referenceTo>Subtask_Template__c</referenceTo>
    <relationshipLabel>Subtask Template Items</relationshipLabel>
    <relationshipName>Subtask_Template_Items</relationshipName>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubtaskChainViewerController/SubtaskChainViewerControllerTest.cls
@IsTest
private class SubtaskChainViewerControllerTest {

    @IsTest
    static void testGetChainsForMatter_groupsStepsByChainInOrder() {
        User staticAssignee = [SELECT Id FROM User WHERE Name = 'David Yeremian' AND IsActive = true LIMIT 1];

        Subtask_Template__c template = new Subtask_Template__c(Name = 'Viewer Test Template');
        insert template;

        insert new List<Subtask_Template_Item__c>{
            new Subtask_Template_Item__c(
                Subtask_Template__c = template.Id,
                Sequence_Order__c   = 1,
                Subject__c          = 'Step One',
                Assignee_Type__c    = 'Static User',
                Static_Assignee__c  = staticAssignee.Id
            ),
            new Subtask_Template_Item__c(
                Subtask_Template__c        = template.Id,
                Sequence_Order__c          = 2,
                Subject__c                 = 'Step Two',
                Assignee_Type__c           = 'Dynamic Matter Field',
                Dynamic_Assignee_Field__c  = 'Senior_Attorney__c'
            )
        };

        NEOS_Matter__c matter = new NEOS_Matter__c(Name = 'Test Matter', Case_Title__c = 'Test Case');
        insert matter;

        SubtaskTemplateApplier.apply(template.Id, matter.Id);

        Test.startTest();
        List<SubtaskChainViewerController.ChainDto> chains = SubtaskChainViewerController.getChainsForMatter(matter.Id);
        Test.stopTest();

        System.assertEquals(1, chains.size());
        System.assertEquals('Viewer Test Template', chains[0].templateName);
        System.assertEquals(2, chains[0].steps.size());
        System.assertEquals('Step One', chains[0].steps[0].subject);
        System.assertEquals('Open', chains[0].steps[0].status);
        System.assertEquals('Step Two', chains[0].steps[1].subject);
        System.assertEquals('Waiting', chains[0].steps[1].status);
    }

    @IsTest
    static void testGetChainsForMatter_returnsEmptyWhenNoChains() {
        NEOS_Matter__c matter = new NEOS_Matter__c(Name = 'Test Matter', Case_Title__c = 'Test Case');
        insert matter;

        Test.startTest();
        List<SubtaskChainViewerController.ChainDto> chains = SubtaskChainViewerController.getChainsForMatter(matter.Id);
        Test.stopTest();

        System.assertEquals(0, chains.size());
    }
}