force-app/main/default/objects/NEOS_Matter__c/NEOS_Matter__c.object-meta.xml
<CustomObject>
    <label>Matter</label>
    <nameField>
        <label>Matter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NEOS_Matter__c/fields/Associate_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Associate_Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associate Attorney</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Associate Attorney</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>NEOS_Matters2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NEOS_Matter__c/fields/Senior_Attorney__c.field-meta.xml
<CustomField>
    <fullName>Senior_Attorney__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Senior Attorney</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Senior Counsel</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Managing Attorney</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>NEOS_Matters1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NEOS_Matter__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Signed</fullName>
                <default>true</default>
                <label>Client Signed</label>
            </value>
            <value>
                <fullName>Administrative Remedies</fullName>
            </value>
            <value>
                <fullName>Complaint Filed</fullName>
            </value>
            <value>
                <fullName>At Issue</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Mediation</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompanionMattersController/CompanionMattersController.cls
public with sharing class CompanionMattersController {

    @AuraEnabled(cacheable=true)
    public static List<NEOS_Matter__c> getCompanionMatters(Id matterId, Integer maxRecords) {
        try {
            NEOS_Matter__c current = [
                SELECT Lawsuit_Matter__c
                FROM NEOS_Matter__c
                WHERE Id = :matterId
                WITH SECURITY_ENFORCED
            ];

            if (current.Lawsuit_Matter__c == null) {
                return new List<NEOS_Matter__c>();
            }

            return [
                SELECT Id, Name, Stage__c, Senior_Attorney__c, Senior_Attorney__r.Name,
                       Associate_Attorney__c, Associate_Attorney__r.Name
                FROM NEOS_Matter__c
                WHERE Lawsuit_Matter__c = :current.Lawsuit_Matter__c
                AND Id != :matterId
                WITH SECURITY_ENFORCED
                ORDER BY Name
                LIMIT :maxRecords
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}